# Site settings
title: Bryan Barrows - Web Developer
description: The personal portfolio of Bryan Barrows
baseurl: "/" # the subpath for the site, e.g. /blog
url: "http://bryanbarrows.me" 

# User settings
username: Bryan Barrows
user_description: I'm a software/web developer based in Seattle, WA. I'm passionate about good design, performant code, and accessibility.
user_title: Software Developer
email: bryanbarrows@live.com
twitter_username: bryanbarrows
github_username:  bbarrows89
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
